[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/Amar Bank - Smart Gateway Homepage.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/digital"
  to = "/digital.html"
  status = 200
